{
 "title": "Nginx Debian Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_connections", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_request_duration_seconds_count"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_request_duration_seconds_count[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of HTTP requests per URI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(nginx_http_uri_total[5m])", "legendFormat": "{{uri}}" }
   ]
  },
  {
   "title": "HTTP request latency per URI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_uri_latency_count[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total of errors requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_metric_errors_total[5m])",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}